### PR TITLE
Aero: Add ground effect, reorganize

### PR DESCRIPTION
**Pull request by Octal450**

### CODE REVIEW

**Comment by l0k1** [comment]
Sorry for the delay!

One issue is at [this diff](https://github.com/l0k1/eurofighter/pull/10/commits/0c834e2f0589c567a9fec75139425da0f96623f6#diff-fff33f9c541e41617bd4c82c59789a7aR3), referencing the IDG-PA28. If you could fix that then I will merge this. Thanks!

**Comment by Octal450** [comment]
Oops! Slipped in there somehow!
Just a name, so won't affect functionality, but I'll fix it today.

Josh

**Comment by l0k1** [comment]
Yup, I am aware it won't affect functionality, but it's better to be clean on this.
Thanks!

**Comment by Octal450** [comment]
Done.

**Comment by l0k1** [comment]
And merged, thank you very much!

**Pull request merged**
