### PR TITLE
Fixes for unknown objects and all errors from the log file

### PR DESCRIPTION
**Pull request by HerbyW**
I know it will be a mess for you. Some things are most probably fixed by you.
As your message in the forum was 2 years old I never thought that you are still working on it.
Maybe we will have 2 versions, one in yasim and one in JSBsim.

### CODE REVIEW

**Comment by l0k1** [comment]
Thank you!

Note that under the new version, various systems and avionics will be implemented in JSBSim, so maintaining two seperate versions doesn't make sense as the workload would increase dramatically. Also beware that I am being very picky about commits to the dev version, please read the readme and ask any questions before submitting a pull request to it.

Thanks again!

**Comment by HerbyW** [comment]
Great! Thanks a lot!
The FG wiki points to the outdated version of FG-addon. I think it would be a good idea to edit the wiki and make a new paragraph with your version as an alternative.
http://wiki.flightgear.org/Eurofighter_Typhoon
I can do this if you have no time.
Is the dev version working? I have not tried it out?

**Comment by l0k1** [comment]
The dev version is working, yes. It only has a HUD and no MFD's yet, and the HUD breaks if you fly upside down. The FDM is very smooth, however.

**Comment by l0k1** [comment]
And yes, feel free to edit the wiki. :)

**Pull request merged**
